[package]
name = "my_contract"
version = "0.1.0"
edition = "2024_07"

[dependencies]
starknet = "2.11.4"

[dev-dependencies]
snforge_std = "0.47.0"

[[target.starknet-contract]]
name = "min_nft"
path = "src/min_nft.cairo"

[scripts]
test = "snforge test"